Disallow customers from logging in if they're archived
BroadleafCommerce/BroadleafCommerce pull request #2021
Opened 2018-11-29 20:42 UTC by cja769

Since `Customer`s aren't sandboxabled the Hibernate filter to filter out archived `Customer`s isn't weaved on therefore in the `UserDetailsServiceImpl` we allow a `Customer` to log in even if they've been archived.

2018-11-29 20:43 UTC, cja769 commented
@phillipuniverse I'm assuming 5.2 is far enough to backport but if not I can rebase it on top of a different line.

2018-12-06 14:45 UTC, phillipuniverse requested changes
Archive status is weaved on in Enterprise (right? or did we move this into core?), you cannot just straight up cast to `Status`. Pretty sure this will blow up in community 💣💣💣💣💣💣💣💣

2018-12-06 16:53 UTC, cja769 commented
@phillipuniverse As you see in ![Uploading Screen Shot 2018-12-06 at 10.52.17 AM.png…](this) screenshot `DirectCopyTransformer` is actually in common and the archiveOnly token is hooked up. I can add a check anyways just in case someone excludes `Customer` from being archivedOnly

2018-12-06 17:15 UTC, phillipuniverse commented
👍 got it. Once you verify that login works with community then we're good to merge.

2018-12-06 17:17 UTC, phillipuniverse commented
Actually, I honestly think this is a p easy defensive coding measure anyway; this could be a class that has other tendrils that people are using in different contexts (without bytecode weaving).

It doesn't really hurt anything to add an `if (Status.isAssignableFrom(customer.getClass()))` to this, so go ahead and do that.

2018-12-06 19:28 UTC, merged