BroadleafEntityValidator.validate() should be public
BroadleafCommerce/BroadleafCommerce pull request #2126
Opened 2019-06-17 17:30 UTC by JustinCRL

**Changes
Removed references to FormFox
Formatted EntityValidatorService

**A Brief Overview**
This required for custom validators to live in alternative packages.  Originally a interface where public is inherited.

**Background
Checking into 5.2.x because I did not see the class in 5.3.x, 5.4.x, and 6.0.x

2019-12-24 16:46 UTC, JustinCRL commented
Why has this not been reviewed.

2019-12-30 18:18 UTC, marieStandeven requested changes
Thank you for your PR, Justin. I'm sorry about the delay in the review process. 

In addition to the suggestion comments, can you update the indentation spacing in the `EntityValidatorServiceImpl.java` file? The standard for Broadleaf Commerce is 4 spaces.

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/BroadleafEntityValidator.java
> + * an add or update occurs. {@link Entity#isValidationFailure()} can be used to see if there core validation found any
```suggestion
 * an add or update occurs. {@link Entity#isValidationFailure()} can be used to see if the core validation found any
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +	private Map<String, List<BroadleafEntityValidator<?>>> broadLeafValidatorMap;
```suggestion
	private Map<String, List<BroadleafEntityValidator<?>>> broadleafValidatorMap;
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +		broadLeafValidatorMap = new HashMap<>(beanNames.length);
```suggestion
		broadleafValidatorMap = new HashMap<>(beanNames.length);
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  			BroadleafEntityValidator<?> formFoxValidator = applicationContext.getBean(beanName,
```suggestion
			BroadleafEntityValidator<?> broadleafValidator = applicationContext.getBean(beanName,
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  						formFoxValidator.getClass().getName(), entityClassName));
```suggestion
						broadleafValidator.getClass().getName(), entityClassName));
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +				List<BroadleafEntityValidator<?>> registeredValidatorsForType = broadLeafValidatorMap
```suggestion
				List<BroadleafEntityValidator<?>> registeredValidatorsForType = broadleafValidatorMap
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +					broadLeafValidatorMap.put(entityClassName, registeredValidatorsForType);
```suggestion
					broadleafValidatorMap.put(entityClassName, registeredValidatorsForType);
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  				registeredValidatorsForType.add(formFoxValidator);
```suggestion
				registeredValidatorsForType.add(broadleafValidator);
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  				LOG.warn("Could not determine entity type for " + formFoxValidator.getClass().getName());
```suggestion
				LOG.warn("Could not determine entity type for " + broadleafValidator.getClass().getName());
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  				LOG.info(String.format("Registering validator %s for entity type %s",
Change references of `formFoxValidator` to `broadleafValidator` on line 81.

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +				// this
```suggestion
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +				// would be the confirmation field for a password validation
```suggestion
				// this would be the confirmation field for a password validation
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +				// the POST
```suggestion
				// the POST and so it will be null
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +				// and so it will be null
```suggestion
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
> +			List<BroadleafEntityValidator<?>> formFoxValidators = broadLeafValidatorMap
```suggestion
			List<BroadleafEntityValidator<?>> broadleafValidators = broadLeafValidatorMap
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  			if (formFoxValidators != null) {
```suggestion
			if (broadleafValidators != null) {
```

2019-12-30 18:18 UTC, marieStandeven commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/validation/EntityValidatorServiceImpl.java
>  				for (BroadleafEntityValidator<?> formFoxValidator : formFoxValidators) {
Change
`formFoxValidators` to `broadleafValidators`
and
`formFoxValidator` to `broadleafValidator`
in lines 232-235.

2019-12-31 18:51 UTC, JustinCRL commented
I changed what you requested.  There is variable called isUpdateRequest which is not used.  Should I remove is as well?

2019-12-31 19:22 UTC, marieStandeven commented
@JustinCRL yes, isUpdateRequest should be removed. Additionally, there are still references to formfox on lines 227-232 at the end of the validate method. 
Change
`formFoxValidators` to `broadleafValidators`
and
`formFoxValidator` to `broadleafValidator`

2020-01-02 14:26 UTC, JustinCRL commented
@marieStandeven done.

2020-01-02 19:59 UTC, merged