Xss protection encoding html entities looks wrong in admin
BroadleafCommerce/BroadleafCommerce pull request #2385
Opened 2020-08-19 11:19 UTC by oleksiimiroshnyk

Xss protection encoding html entities looks wrong in admin
fixes BroadleafCommerce/QA#4142

- if this is "string field" and not "large entry" and xss protection enabled content of the field will be unHtmlEscaped before rendering
- when data sent to solr if exploitProtection.xssEnabled is enabled on admin node exploitProtection.xssEnabled should be also enabled on the node that's responsible for solr indexing - it will unHtmlEscaped fields.
- "q" parameter is added to whitelist, so searching on site should be not encoded

2020-08-19 13:54 UTC, StanislavFedorov approved these changes

2020-08-27 21:25 UTC, cja769 requested changes
Couple questions about the changes

2020-08-27 21:25 UTC, cja769 commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
> -                .append(products)
Why was this change made?

2020-08-27 21:25 UTC, cja769 commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
> +                return StringEscapeUtils.unescapeHtml((String) propertyValueInternal);
Why do we check this property here but not in the other changes in `FormBuilderServiceImpl`?

2020-08-27 21:25 UTC, cja769 commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
> +        } else if (!attributeValue.equals(other.attributeValue)) {
What's the reason for these changes?

2020-08-27 21:25 UTC, cja769 commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionValueImpl.java
> +        return Objects.hash(id, attributeValue);
What's the reason for this change?

2020-08-27 21:25 UTC, cja769 commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/catalog/domain/ProductOptionImpl.java
> -                .append(this.products, rhs.products)
Why was this change made?

2020-08-27 21:36 UTC, cja769 commented
I resolved some of the comments I made because I realized that they were the changes made from https://github.com/BroadleafCommerce/BroadleafCommerce/pull/2396. I'll merge 5.2 into 6.0 and rebase this branch

2020-09-07 08:02 UTC, oleksiimiroshnyk commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/search/service/solr/SolrHelperServiceImpl.java
> +                return StringEscapeUtils.unescapeHtml((String) propertyValueInternal);
@cja769 I think solr helper I was fixing representation from search/search capabilities on site.
SolrHelper is used in site, and maybe indexing, and FormBuilder is used in admin. So this is completely different places and they don't share anything common

2020-09-08 16:14 UTC, cja769 approved these changes

2020-09-15 14:38 UTC, merged