Fixed 403 error when page refreshes
BroadleafCommerce/BroadleafCommerce pull request #2695
Opened 2022-06-15 13:37 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4723

I changed the logic to use extension handler and changed a validation logic so it can use parent id of product

2022-06-15 14:55 UTC, danielcolgrove requested changes

2022-06-15 14:55 UTC, danielcolgrove commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
> +                    property.setValue(sectionCrumbOptional.get().getSectionId());
You can't change the property.  The solution should be similar to https://github.com/BroadleafCommerce/Enterprise/pull/1452 in that we need to take the property id and find its parent.  The issue here is that this code is in framework and the logic we need is in Enterprise.  So we will likely need an ExtensionHandler to call into Enterprise to get the parent id.

2022-06-21 13:54 UTC, KatrukOV commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/handler/ParentIdServiceExtensionManager.java
> +    public ParentIdServiceExtensionManager(){super(BasicParentIdServiceExtensionHandler.class);}
use code formatting

2022-06-21 13:54 UTC, KatrukOV commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/server/service/persistence/PersistenceManagerImpl.java
> +                           String parentID = extensionResultHolder.getResult();
AbstractParentIdServiceExtensionHandler.checkParentId() always return ExtensionResultStatusType.NOT_HANDLED;

Is it correct?

2022-07-11 16:27 UTC, riteshadhikari17 approved these changes

2022-07-11 16:30 UTC, danielcolgrove approved these changes

2022-07-11 16:31 UTC, merged