Fixed issue with translation of product options
BroadleafCommerce/BroadleafCommerce pull request #2718
Opened 2022-08-30 14:36 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4771

Added some logic which compares option value to key and translates product

2022-08-30 14:43 UTC, danielcolgrove requested changes

2022-08-30 14:43 UTC, danielcolgrove commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
> +import org.broadleafcommerce.core.catalog.domain.*;
We don't want to use wildcard imports.

2022-08-30 16:06 UTC, danielcolgrove approved these changes

2022-09-01 07:53 UTC, oleksiimiroshnyk approved these changes

2022-09-01 07:53 UTC, oleksiimiroshnyk commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/order/service/OrderItemServiceImpl.java
> +                List<ProductOptionValue> optionValues = ((DiscreteOrderItem) item).getSku().getProductOptionValues();
I think we can extract this to some method, like String getTranslatedValue(String key) ?

Also getProductOptionValues looks like deprecated let's don't use deprecated in new code ?

2022-09-08 13:11 UTC, oleksiimiroshnyk requested changes
there is a discussion going on in helpscout if this is reasonable or not to do this change.
So let;'s wait and don't merge till then

2022-09-08 15:39 UTC, closed without merging