Updated Indexes in BroadleafCommerce module
BroadleafCommerce/BroadleafCommerce pull request #2721
Opened 2022-09-06 13:32 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4782

Hibernate Index annotation become deprecated, so I used JPA @Index instead. Updated all places

2022-09-06 14:02 UTC, danielcolgrove requested changes

2022-09-06 14:02 UTC, danielcolgrove commented on core/broadleaf-framework/src/main/java/org/broadleafcommerce/core/payment/domain/OrderPaymentImpl.java
> +                                    @Index(
Let's fix the tabbing on this section

2022-09-07 14:28 UTC, KatrukOV commented on admin/broadleaf-contentmanagement-module/src/main/java/org/broadleafcommerce/cms/structure/domain/StructuredContentImpl.java
> +        @Index(name="CONTENT_NAME_INDEX", columnList = "CONTENT_NAME , ARCHIVED_FLAG , SC_TYPE_ID"),
Error: database column 'ARCHIVED_FLAG' not found;
Check columns and names in DB (there is an "ARCHIVED" column in BLC_SC)

2022-10-13 20:07 UTC, riteshadhikari17 commented
There are test failures

2022-10-26 17:13 UTC, closed without merging