Upgraded HSQL version to 2.7.1
BroadleafCommerce/BroadleafCommerce pull request #2746
Opened 2022-11-02 13:45 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4813

Updated hsql to version 2.7.1 Also had to add classifier parameter to hsql dependency, because by default it needs JDK-11

2022-11-02 13:49 UTC, oleksiimiroshnyk approved these changes

2022-11-07 23:05 UTC, riteshadhikari17 requested changes

2022-11-07 23:05 UTC, riteshadhikari17 commented on admin/broadleaf-open-admin-platform/pom.xml
> +            <version>2.7.1</version>
No need to define version on each of the POMs. It should come from parent POM. Not sure about the classifier so maybe test without it first.

2022-11-07 23:05 UTC, riteshadhikari17 commented on common/pom.xml
> +            <version>2.7.1</version>
Same as above

2022-11-07 23:05 UTC, riteshadhikari17 commented on integration/pom.xml
> +            <version>2.7.1</version>
same as above

2022-11-08 14:51 UTC, danielcolgrove commented
The classifier should be in the project pom (not the parent pom).  Only the version would be in the parent pom.  The project pom can decide if it needs a classifier which we should use classifier as needed.

2022-11-08 15:41 UTC, riteshadhikari17 commented
@danielcolgrove Classifier is needed for us because we use jdk8 when building. These are needed for ITs only. What if we add test scope to all ? Like this
```
  <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <classifier>jdk8</classifier>
      <scope>test</scope>
  </dependency>
```

2022-11-08 16:42 UTC, danielcolgrove commented
Using the scope should be fine when the scope is needed - for "test" is a good example of when you would want it.

2023-01-13 16:09 UTC, riteshadhikari17 approved these changes

2023-01-13 16:57 UTC, merged