Update GA to version 4
BroadleafCommerce/BroadleafCommerce pull request #2762
Opened 2022-12-20 11:29 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4848

Updated to GA4.
Created a custom thymeleaf processor for new version of GA

2023-02-08 15:46 UTC, oleksiimiroshnyk requested changes

2023-02-08 15:46 UTC, oleksiimiroshnyk commented on core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/GoogleAnalytics4Processor.java
> +        StringBuffer sb = new StringBuffer();
guess StringBuilder is better ? Buffer is synch which is not needed here

2023-02-08 15:46 UTC, oleksiimiroshnyk commented on core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/GoogleAnalytics4Processor.java
> +        StringBuffer sb = new StringBuffer();
builder instead of buffer

2023-02-08 16:15 UTC, oleksiimiroshnyk commented on core/broadleaf-framework-web/src/main/java/org/broadleafcommerce/core/web/processor/GoogleUniversalAnalyticsProcessor.java
>          StringBuffer sb = new StringBuffer();
one more buffer

2023-03-03 11:19 UTC, oleksiimiroshnyk approved these changes

2023-03-16 13:22 UTC, riteshadhikari17 commented
@MarekB01 @oleksiimiroshnyk I don't know how to test this. Have you guys done any testing? If you guys are confident about this, you can simply merge it.

2023-04-03 20:47 UTC, Jerry77oz commented
@MarekB01 this looks like we're good to merge this, anything you think we could test before we do?

2023-04-12 11:57 UTC, oleksiimiroshnyk commented
used docs for migration:
https://developers.google.com/analytics/devguides/migration/ecommerce/analyticsjs-before-you-begin\
https://developers.google.com/analytics/devguides/migration/ecommerce/gtagjs-ua-to-ga4
https://support.google.com/analytics/answer/9310895#gtagjs-enable-basic&zippy=%2Cin-this-article
https://support.google.com/analytics/answer/10759417
https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article

new property for tag id: googleAnalytics4.tagIdForProperty

2023-05-04 15:16 UTC, merged