Qa 4914 preview status changes
BroadleafCommerce/BroadleafCommerce pull request #2807
Opened 2023-03-10 15:34 UTC by MarekB01

https://github.com/BroadleafCommerce/QA/issues/4914

Added comments about a web request scope so checkbox will save state for a whole session

2023-03-10 15:50 UTC, oleksiimiroshnyk requested changes

2023-03-10 15:50 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
> +            request.removeAttribute("blIncludeMyChanges", WebRequest.SCOPE_SESSION);
let's extract blIncludeMyChanges to "constant" and re-use, similar to BroadleafSandBoxResolver.SANDBOX_ID_VAR

2023-03-10 15:50 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafSandBoxResolverImpl.java
> +            if (request.getParameter("blIncludeMyChanges") != null) {
let's re-use constant that will be extracted

2023-03-10 15:50 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafSandBoxResolverImpl.java
> +                    request.removeAttribute("blIncludeMyChanges", WebRequest.SCOPE_SESSION);
here also

2023-03-14 08:52 UTC, oleksiimiroshnyk requested changes

2023-03-14 08:52 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
> +    private static final String INCLUDE_MY_CHANGES_VAR = "blIncludeMyChanges";
I think we can delete this and use BroadleafIncludeMyChangesResolver.INCLUDE_MY_CHANGES_VAR

2023-03-14 08:52 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
> +                        if(hsr.getParameter(INCLUDE_MY_CHANGES_VAR) != null){
reuse BroadleafIncludeMyChangesResolver.INCLUDE_MY_CHANGES_VAR

2023-03-14 08:52 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafRequestProcessor.java
> +                            url.append("&blIncludeMyChanges="+hsr.getParameter(INCLUDE_MY_CHANGES_VAR));
here. instead of &blIncludeMyChanges=
reuse 
"&"+BroadleafIncludeMyChangesResolver.INCLUDE_MY_CHANGES_VAR+"="

2023-03-14 08:52 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafSandBoxResolverImpl.java
> +            if (request.getParameter(INCLUDE_MY_CHANGES_VAR) != null) {
reuse BroadleafIncludeMyChangesResolver.INCLUDE_MY_CHANGES_VAR

2023-03-14 08:52 UTC, oleksiimiroshnyk commented on common/src/main/java/org/broadleafcommerce/common/web/BroadleafSandBoxResolverImpl.java
> +                    request.removeAttribute(INCLUDE_MY_CHANGES_VAR, WebRequest.SCOPE_SESSION);
reuse BroadleafIncludeMyChangesResolver

2023-03-14 11:17 UTC, oleksiimiroshnyk approved these changes

2023-03-15 20:26 UTC, riteshadhikari17 commented
I am seeing an issue where it is saying access denied but if I refresh it, it works. Here is the video

https://user-images.githubusercontent.com/35038090/225434043-924763b5-2737-45e0-bee2-ac3e3d41ef06.mov

2023-03-16 12:36 UTC, MarekB01 commented
@riteshadhikari17 it acts quiet strange, I just retested it and it works fine for me, I dont get this 403 error, and changes are passing

2023-03-16 14:17 UTC, riteshadhikari17 commented
I still see the error after erasing and rebuilding DB and M2. This is the exact error
```
org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "'locale-' + session.blLocale.localeCode" (template: "layout/homepage" - line 9, col 7)
EL1007E: Property or field 'localeCode' cannot be found on null
```

2023-03-16 15:37 UTC, merged