Got rid of old spring-social dependency
BroadleafCommerce/BroadleafCommerce pull request #2858
Opened 2023-08-01 11:33 UTC by MarekB01

Related to: https://github.com/BroadleafCommerce/QA/issues/4974

Removed spring-social dependency as it became deprecated. Rewrote BroadleafSocialRegisterController to use OAuth2 implementation.

2023-08-01 13:28 UTC, riteshadhikari17 commented
This is the error in jenkins
```
[ERROR]     'dependencies.dependency.version' for org.springframework.security:spring-security-oauth2-client:jar is missing. @ line 101, column 21
```

FYI Module Parent is for modules. Core does not use MP. Define the version here and close the PR for MP.

2023-08-21 14:37 UTC, MarekB01 commented
Now it can be merged

2023-08-21 14:46 UTC, riteshadhikari17 commented on core/broadleaf-profile-web/pom.xml
> +            <version>5.5.3</version>
Don't define version here. It should come from root pom.

2023-08-22 14:38 UTC, riteshadhikari17 commented on pom.xml
> +                <version>6.0.2</version>
This version needs to sync with spring security. We define it as property above so use it.
`${spring.security.version}`. Also shouldn't you remove the spring-social dependency below?

2023-08-23 08:02 UTC, oleksiimiroshnyk requested changes

2023-08-23 08:02 UTC, oleksiimiroshnyk commented on core/broadleaf-framework-web/pom.xml
> +        <dependency>
I see you've added a new dependency, but what about deleting old spring social ? Is it still there ?

2023-08-23 18:58 UTC, riteshadhikari17 approved these changes

2023-08-25 15:13 UTC, oleksiimiroshnyk approved these changes

2023-08-25 15:25 UTC, merged