Using the Time Zone Setting
BroadleafCommerce/BroadleafCommerce pull request #2911
Opened 2023-10-15 22:00 UTC by KatrukOV

**A Brief Overview**
a new method formatSimpleDate() has been added to BLCDateUtils; 
extracted logic for setting the date in RecordField into a separate method (FormBuilderServiceImpl.setDateToRecordField())

**Link to QA issue**
[QA-5089](https://github.com/BroadleafCommerce/QA/issues/5089)

2023-10-16 07:51 UTC, StanislavFedorov approved these changes

2023-10-18 10:07 UTC, oleksiimiroshnyk requested changes

2023-10-18 10:07 UTC, oleksiimiroshnyk commented on admin/broadleaf-open-admin-platform/src/main/java/org/broadleafcommerce/openadmin/web/service/FormBuilderServiceImpl.java
> +                            this.setDateToRecordField(recordField, p);
you create a new formatter in this method, I don't see why do we need it to create in loop, extract it and pass as a parameter if you need this method

2023-10-24 08:52 UTC, oleksiimiroshnyk approved these changes

2023-11-07 09:30 UTC, merged