Fixed an issue where the discount value was displayed incorrectly
BroadleafCommerce/BroadleafCommerce pull request #2941
Opened 2023-11-30 15:08 UTC by KatrukOV

**A Brief Overview**
Uses decimalSeparator to manipulate the value in OfferCustomPersistenceHandler.fetch()

**Link to QA issue**
[QA-5156](https://github.com/BroadleafCommerce/QA/issues/5156)

2023-11-30 15:57 UTC, oleksiimiroshnyk requested changes

2023-11-30 15:57 UTC, oleksiimiroshnyk commented on admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
> +            } else {
why else {
if(){
and not else if ?

2023-11-30 15:57 UTC, oleksiimiroshnyk commented on admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
> +                                .replaceAll(String.format("\\%s$", decimalSeparator), "");
why do we need String.format("\\%s$", decimalSeparator) ?
and not just \\+decimalSeparator

2023-11-30 15:57 UTC, oleksiimiroshnyk commented on admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
> +                } else {
else if ?

2023-11-30 15:57 UTC, oleksiimiroshnyk commented on admin/broadleaf-admin-module/src/main/java/org/broadleafcommerce/admin/server/service/handler/OfferCustomPersistenceHandler.java
> +                        .replaceAll(String.format("\\%s", decimalSeparator), "")
String.format("\\%s", decimalSeparator)  ?

2023-12-01 10:58 UTC, oleksiimiroshnyk approved these changes

2023-12-01 15:38 UTC, Jerry77oz approved these changes

2023-12-01 15:39 UTC, Jerry77oz commented
@KatrukOV looks good, could you provide a hotfix file (where you extend the class and override methods as needed with the fix) so we can send it to the client?

2023-12-21 11:29 UTC, merged